### ISSUE TITLE
Bower installation doesn't build the package

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/app-header#20]
I have a need of getting the **app header** installed as a bower dependency. And since this is not available in bower registry, I installed this by the git URL. But, then the problem is, the project is not built. 

I tried adding .bowerrc and it didn't work. Is there any way you can help on this. I would like to do the required patch if possible.
```
{
  "scripts": {
    "postinstall": "npm install && npm run build"
  }
}
```

As a suggestion, how about committing the build folder with the releases which might be even possible to automate in a Travis trigger.

**Comment by wyseguyonline** [comment]
We do not include build files in our repositories in order to keep our repos small and not include unnecessary files.  This is a standard practice.

Unfortunately we do not support bower in any fashion.  I would recommend looking into the following:
https://www.npmjs.com/package/bower-npm-resolver

This is an npm module that appears to be designed to assist with projects that use bower but need a better way to handle npm-based packages.  Please note, no one on the team has used this package so we would be unable to assist in configuration or execution of this module.

To more specifically troubleshoot the issue, it is unclear why the postinstall commands aren't working other than to suggest that they're likely running an npm install on the root level of the project rather than the root of the app-header module.  If the bower-npm-resolver does not fix the issue, the recommendation would be to write a shell script (or batch file) that goes into the app-header directory and runs the npm install and npm run build commands there.  Then have the postinstall hook call that shell script.

Ultimately, we recommend teams move from bower to npm to handle package management.  NPM is the package management tool recommended by Enterprise Architecture.  While the shift from one tool to the other can be daunting, the following article should help with easing that transition.  

https://gofore.com/stop-using-bower/
