### ISSUE TITLE
Suggestions for demo pages

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/app-header#24]
Hi,

These days I'm working on integrating the app-header into few templates in Learning Apps Framework. And then I was thinking how my much my work could have been easier if the demo pages were available online with the sample codes as well. Let me add following suggestions.

- Enabling access to demo pages via github.io 
- Simplifying the demo code. So, that anyone can copy it to anyway easily.
- Displaying the demo code somewhere in the page. (May be in the page body with more descriptions)
- Adding few examples with pi session authentication
 
Regards,
Dinuka

**Comment by StommePoes** [comment]
Hi!
a few things:
1. it's definitely in the planning to have (externally hosted) demos... currently we only have one (and it is on github) however Github does have some restrictions about hosting content. But yes, the future holds live demos online!
2. The current app-header is some weird javascript-templating thing written by a team-member who left long ago, before we had our tech stack well-defined. To get it ready in time for the rebrand, this caused us to use images (pngs) because this templating thing doesn't understand SVGs. The plan is sometime in Q3 to make this a full React component, which will simplify the code and also remove the external images stuff. The old account dropdown also got restyled to look like the help drawer in rebranding, so in Q3 the actual, real help drawer will be used as well (if this design decision remains).
3. Displaying the actual demo code, for example on the demo page itself, is a good idea. Something like we're doing for HTML on Elements? http://pearson-higher-ed.github.io/elements/elements/buttons/

Some of this feedback will still probably turn into tech-debt tickets for us. Thanks!

**Comment by mhomolak** [comment]
This has been done for our other components and will be done for app-header when the React rewrite happens.
