### ISSUE TITLE
Options are not being updated at the first attempt

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/app-header#26]
I have the following code in my application

```
var element = document;
var config = {
	mode: 'Basic',
	user: {
		givenName: 'John'
	}
};
document.dispatchEvent(new CustomEvent('o.DOMContentLoaded', {
                detail: {
                    element: element,
                    config: config
                }
            }));
```

Here is the output. And this doesn't show the username and keep remains signed out. 

**v1.1.2**
![image](https://cloud.githubusercontent.com/assets/10680296/24897288/008e5842-1eb6-11e7-9c04-7af64806d09a.png)

**v2.0.5**
![image](https://cloud.githubusercontent.com/assets/10680296/24897380/565f85ac-1eb6-11e7-92f4-3dff6e2c6ce9.png)

And if I append the following code after the above.
```
document.dispatchEvent(new CustomEvent('o.DOMContentLoaded', {
                detail: {
                    element: element,
                    config: config
                }
            }));
```

**v1.1.2**
![image](https://cloud.githubusercontent.com/assets/10680296/24897318/24a4155a-1eb6-11e7-87f8-e955e395cce9.png)

**v2.0.5**
![image](https://cloud.githubusercontent.com/assets/10680296/24897405/6fc8dade-1eb6-11e7-8547-d8e66bf498c4.png)

**summary**

As a summary, this seems not specific to the latest version and initial event seems doesn't accept the options.

Regards,
@dinukadesilva

**Comment by wyseguyonline** [comment]
It is a little unclear why attaching the element and config to the window object is being done here.  This is an approach that seems likely to run into conflicts with other code that is also using the global namespace.  In general, it is strongly recommended to not use the global namespace for something like this. 

The first example is displaying behavior that is consistent with falsey (e.g. undefined, null, etc.) values being passed in for config and/or element.  It suggests that either the window object itself isn't available when the first event is dispatched but is available when the second (indicating a load timing issue) or is otherwise not passing the correct values to the app-header.  The app-header does a fairly thorough job of reverting to defaults when incorrect data is passed into it.  I would recommend using locally scoped variables for element and config and seeing if that changes things.  

In order to troubleshoot this better, the information contained in the JavaScript console (if any) would be helpful.

**Comment by dinukadesilva** [comment]
Could you please look at the updated example above. I just updated that. This behavior is a bit sporadic and I noticed that this happens only at the first two attempts. And seems it happens based on the validity of the input element. I assume this is an issue in the following code segment which seems triggered only at the first attempt.

[![image](https://cloud.githubusercontent.com/assets/10680296/25274787/615a5292-26af-11e7-8719-ab6425416c71.png)](https://github.com/Pearson-Higher-Ed/app-header/blob/master/src/js/AppHeader.js#L73)
https://github.com/Pearson-Higher-Ed/app-header/blob/master/src/js/AppHeader.js#L73

**Comment by wyseguyonline** [comment]
I'm not sure why you're attempting to instantiate two app-header instances using the same set parameters.  The first example is consistent with what we would expect when passing in something that isn't an instance of HTMLElement.  The document object is not an instance of HTMLElement and will be assumed to be the configuration object which doesn't have any of the attributes the app-header is looking for so the default behavior in the first example is exactly what we would expect with the code you've provided (i.e. app-header in signed out mode).

After discussing this with the team, we will be refactoring the incoming parameters check to insist upon a valid instance of an HTMLElement and a separate object for config (complete with errors thrown which will cause the app-header to not display if it isn't passed valid parameters).  I'm not sure when this will get released, but it should be coming soon.

For the time being, please change var element = document; to something that is an actual valid HTMLElement, or leave it out entirely and you should see things start to work correctly.
