### ISSUE TITLE
Isn't there a way to keep the app header as not fixed top 

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/app-header#32]
https://github.com/Pearson-Higher-Ed/app-header/blob/master/src/js/AppHeader.js#L178

**Comment by StommePoes** [comment]
You could, either by removing that line OR in your own page's CSS, add
.o-header--fixed {position:static;}

BUT

You ought to run this by the UXF designers because I'm hearing their goal is everyone's Pearson pages look the same. Otherwise app-header would have had it as an [option] for the stickiness.

If you get the OK from Design to have a non-sticky header, then we might be able to have that be an option you set rather than it hard-coded. Let us know.

**Comment by dinukadesilva** [comment]
yp.... that's true @StommePoes 

Thanks.

**Comment by dinukadesilva** [comment]
But, in that case, how should be the status banner added. Should it be like this?

![image](https://user-images.githubusercontent.com/10680296/26973176-c17d6e44-4d32-11e7-95b1-913e477e39f3.png)

**Comment by wyseguyonline** [comment]
Yes.  The app header is intended to be at the top of any Pearson application with all notifications, banners, and content being below it.  System status messages like the one shown should appear below the application header.

**Comment by dinukadesilva** [comment]
Thanks @wyseguyonline
